### ISSUE TITLE
Test with my own video

### ISSUE THREAD

**Issue by KrisHeegyeong** [alzayats/DeepFish#12]
Hi, Your work seems interesting and I ran the code you've mentioned.  Thank you for your guide, #1, I ran this and I got some video but it's just seriese of  results for the single pictures and it doesn't segment well. I am studying the code flow you made but I barely could find how to get good [results](https://github.com/alzayats/DeepFish/blob/master/docs/seg.gif) like you uploaded. Could you give some advice regarding that?

**Comment by alzayats** [comment]
Hi,

Thank you for your interest in our work and for trying out the code.

Here are a few suggestions that might help:
Check the Input Data: Make sure the images you’re using for testing are similar in size to the images used for training the model. The model might not perform well if the test images are very different from the training images.
Model Training: If you’re still not getting good results, it might be necessary to retrain the model with more data or for more epochs.

I hope these suggestions help.

**Comment by KrisHeegyeong** [comment]
@alzayats Thank you for your answer :) I am Ph.D. student in Macquarie university working on tracking submarine animal project and your work seems really helpful for me to start my work. 

I used the data uploaded in the repository and I got result like this. Do I need to run training more than 50 times as it is written in train_single_image.py? 

![Screenshot_from_2024-03-01_16-21-38](https://github.com/alzayats/DeepFish/assets/83979274/32154c68-dc12-4252-8397-108794499950)
![Screenshot_from_2024-03-01_16-22-25](https://github.com/alzayats/DeepFish/assets/83979274/ebc2f721-69b6-4d67-aa44-1517b39032cb)

**Comment by alzayats** [comment]
Hi Kris,

Based on the results you’ve shared, it seems like the segmentation might not be as accurate as expected. The train_single_image.py script is indeed just a demo and typically, more than 50 epochs would be needed to achieve good results.

If you’re working with the same image, I recommend continuing the training for more epochs until the model’s performance improves. However, if you’re planning to predict different images, please use the trainval.py script and run it for several epochs. This should help in achieving better segmentation results.

Remember, the number of epochs might vary depending on the complexity of the images and the capacity of the model. Keep an eye on the model’s performance metrics during training to decide when to stop.

Best of luck with your project!

**Comment by KrisHeegyeong** [comment]
Thank you for your advice :)
