### ISSUE TITLE
Depth map

### ISSUE THREAD

**Issue by Art3miss233** [alzayats/DeepFish#14]
Hello, 

In your README you write that depth and the map coordinates of the cameras were collected. I am wondering if this data is public or not? I am evaluating some depth estimation methods in my thesis, and it would be incredibly valuable to have such ground truth data to assess the methods against.

**Comment by alzayats** [comment]
Hello,

Thank you for your interest in our work. However, I’m sorry but we are not open to sharing the depth and map coordinates data publicly due to privacy and security reasons. I hope you understand. Good luck with your thesis!

**Comment by Art3miss233** [comment]
Okay, thank you for the quick reply! Keep up the cool work!
