### ISSUE TITLE
```vis_on_batch``` code block issue  

### ISSUE THREAD

**Issue by DoranLyong** [alzayats/DeepFish#2]
As your [previous suggestion and guidance](https://github.com/alzayats/DeepFish/issues/1#issue-748188552), I have been understanding the code flow. I want to say thank you. <br/> 

I have a few more questions about ```vis_on_batch()``` code block in [loc_wrapper.py](https://github.com/alzayats/DeepFish/blob/master/src/wrappers/loc_wrapper.py).  I finally got some results for ```img_mask``` as below .
![image](https://user-images.githubusercontent.com/13333380/101317584-1a2dd200-38a2-11eb-8b11-8c4205378648.png)

However, I can't get any result from ```img_points```. It seems that the line 139,  ```points = hu.zoom(batch["points"],11).squeeze()```, returns nothing. <br/>

 Actually, the error said ```haven-ai``` has no attribute ```zoom```. When I checked this part in the [haven-ai](https://github.com/haven-ai/haven-ai/tree/master/haven/haven_utils) and I found out nothing, so  I changed this line as [ndimage.zoom(batch["points"],11).squeeze()](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.zoom.html), which I think this is you may want? But, But, the system blocked and dead whenever run this line.  How to fix this line?

**Comment by IssamLaradji** [comment]
Hi @DoranLyong I have fixed these issues, 

1) Please install the following `pip install git+https://github.com/ElementAI/LCFCN`

2) Then run 

```
python scripts/train_single_image.py -e loc -d ${PATH_TO_DATASET}
```

you should get something like this,

![image](https://user-images.githubusercontent.com/3382128/102640980-54606480-4129-11eb-9e08-2e5976cfc270.png)

Left hand side is the ground truth, middle is the prediction, right is the heatmap of the network. Let me know if you face issues.

**Comment by DoranLyong** [comment]
Oh! thank you @IssamLaradji  !!!
I really appreciate your works. It works as you instructed.  For now, I can study more myself with this. 
Thank you :)

**Comment by IssamLaradji** [comment]
you welcome! :))
