### ISSUE TITLE
Segmentation JSON files

### ISSUE THREAD

**Issue by BenMaslen** [alzayats/DeepFish#4]
Hi I was wondering if you could provide the JSON files for your segmentation dataset if it is readily available?

**Comment by alzayats** [comment]
Hi, unfortunately, we don't have a JSON files for your segmentation dataset.

**Comment by IssamLaradji** [comment]
But the segmentation masks should be here: https://cloudstor.aarnet.edu.au/plus/s/NfjObIhtUYO6332

**Comment by BenMaslen** [comment]
No worries, thought I would ask before I attempt to generate the polygons from your image masks. Thank you for your quick responses!
