### ISSUE TITLE
Error  : 'game_monitor' in Segmentation part

### ISSUE THREAD

**Issue by Dikec** [alzayats/DeepFish#6]
Hello,
thank you for your work, as much for the database as for the application you made of it.
I am particularly interested in the segmentation part.
I have already been able to run the learning and testing on a single image, it works great.
However, when I try to run the whole learning for segmentation, I get an error .

I do : `python trainval.py -e seg -sb ${path_result} -d ${path_dataset} -r 1 -uc 1`

And I have this error : 

>  TypeError: val_on_loader() missing 1 required positional argument: 'game_monitor'

I understand that in the file "seg_wrapper", you call val_on_loader() of __init__.py of wrapper directory. 
val_on_loader() takes 4 arguments (model, val_loader, val_monitor, game_monitor), but in seg_wrapper.py you call the function without game_monitor.
Is this normal? How can I fix this?

Thank You for your Help

**Comment by alzayats** [comment]
Hi,
Thanks for pointing out this bug.
I have removed game_monitor. Now it should work!
Please confirm.
Thanks

**Comment by alzayats** [comment]
Hi,
I have fixed the bug, please check.

**Comment by Dikec** [comment]
Hi,

Perfect, it's good now, thank you very much for your help ! 

Best regards
